apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      version: ">=1.0.0-production"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - nginx.production